backend = "full"
palette = "dark16"
check_contrast = true
threshold = 7

[templates]
hyprland = { src = 'colors-hyprland.conf', dst = '~/.cache/wallust/colors-hyprland.conf' }
hyprpaper = { src = 'hyprpaper.conf', dst = '~/.config/hyprland/hyprpaper.conf' }
mako = { src = 'mako_config', dst = '~/.config/mako/mako_config' }
tofi = { src = 'tofi-colors', dst = '~/.cache/wallust/tofi-colors' }
kitty = { src = 'colors-kitty.conf', dst = '~/.cache/wallust/colors-kitty.conf' }
waybar = { src = 'colors-waybar.css', dst = '~/.cache/wallust/colors-waybar.css' }
nvim = { src = 'colors_neopywal.vim', dst = '~/.cache/wallust/colors_neopywal.vim' }
