backend = "full"
palette = "dark16"
check_contrast = true
threshold = 7
saturation = 20

[templates]
hyprland = { src = 'colors-hyprland.conf', dst = '~/.cache/wallust/colors-hyprland.conf' }
kitty = { src = 'colors-kitty.conf', dst = '~/.cache/wallust/colors-kitty.conf' }
mako = { src = 'mako_config', dst = '~/.config/mako/config' }
nvim = { src = 'colors_neopywal.vim', dst = '~/.cache/wallust/colors_neopywal.vim' }
obsidian = { src = 'colors-obsidian.css', dst = '~/Documents/Drive/Obsidian/.obsidian/snippets/colors-obsidian.css' }
tofi = { src = 'tofi-colors', dst = '~/.cache/wallust/tofi-colors' }
vesktop = { src = 'colors-discord.css', dst = '~/.config/vesktop/themes/colors_discord.css' }
vesktop_mac = { src = 'colors-discord.css', dst = '~/Library/Application Support/vesktop/themes/colors-discord.css' }
waybar = { src = 'colors-waybar.css', dst = '~/.cache/wallust/colors-waybar.css' }
